name: 🎯 Detection Rule Request
description: Request a new detection rule or modify existing rule
title: "[DETECTION] "
labels: ["detection-rule", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Detection Rule Development
        Use this template to request new detection rules or modifications to existing rules.

  - type: dropdown
    id: rule-type
    attributes:
      label: Rule Type
      description: What type of detection rule is this?
      options:
        - New Rule
        - Rule Modification
        - Rule Tuning (False Positive Reduction)
        - Rule Deprecation
    validations:
      required: true

  - type: input
    id: rule-name
    attributes:
      label: Rule Name
      description: Descriptive name for the detection rule
      placeholder: "e.g., Suspicious PowerShell Execution with Encoded Commands"
    validations:
      required: true

  - type: dropdown
    id: siem-platform
    attributes:
      label: Target SIEM Platform
      description: Which SIEM platform is this rule for?
      options:
        - Elastic Security
        - Azure Sentinel
        - Splunk
        - Chronicle
        - Multiple Platforms
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Rule Severity
      description: Expected severity level for alerts generated by this rule
      options:
        - Critical
        - High
        - Medium
        - Low
        - Informational
    validations:
      required: true

  - type: textarea
    id: threat-description
    attributes:
      label: Threat Description
      description: Describe the threat or behavior this rule should detect
      placeholder: This rule detects adversaries using PowerShell with base64 encoded commands to evade detection...
    validations:
      required: true

  - type: textarea
    id: detection-logic
    attributes:
      label: Detection Logic
      description: Describe the detection logic or provide a draft query
      placeholder: |
        Query logic:
        - Process name contains "powershell.exe"
        - Command line contains "-encodedcommand" or "-enc"
        - Exclude known administrative scripts
      render: markdown
    validations:
      required: true

  - type: input
    id: mitre-technique
    attributes:
      label: MITRE ATT&CK Technique
      description: Primary technique this rule covers (e.g., T1059.001)
      placeholder: "T1059.001"
    validations:
      required: false

  - type: textarea
    id: data-sources
    attributes:
      label: Required Data Sources
      description: What data sources are needed for this rule?
      placeholder: |
        - Windows Event Logs (Security, Sysmon)
        - EDR telemetry
        - Network logs
    validations:
      required: true

  - type: textarea
    id: false-positives
    attributes:
      label: Known False Positives
      description: Document known false positive scenarios
      placeholder: |
        - Administrative scripts run by IT team
        - Legitimate software updates
        - Automated deployment tools
    validations:
      required: false

  - type: textarea
    id: testing-plan
    attributes:
      label: Testing & Validation Plan
      description: How should this rule be tested?
      placeholder: |
        1. Test with historical data from last 30 days
        2. Validate against known attack simulations
        3. Monitor for 7 days in test environment
    validations:
      required: false

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Checklist for rule deployment
      options:
        - label: Rule tested with historical data
        - label: False positive rate < 5%
        - label: Documented in detection matrix
        - label: Peer reviewed by SOC team
        - label: Playbook created for response
